theme: jekyll-theme-cayman
title: Savage Beginner's Guide
description: If you're a slow learner like me, this is your place for taking your time and understanding mechanics. Specially written for people like me who need detailed descriptions of mechanics and who feels details in videos lack attention.
credits: All the guides I used to get where I am.
